// <auto-generated />
using System;
using IAMS.Api.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IAMS.Api.Common.Persistence.Migrations
{
    [DbContext(typeof(IamsDbContext))]
    [Migration("20260916074619_AddInventoryAndScanning")]
    partial class AddInventoryAndScanning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IAMS.Api.Common.Domain.Bin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SyncCursorUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasComputedColumnSql("COALESCE(\"UpdatedAtUtc\", \"CreatedAtUtc\")", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RackId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("CompanyId", "SyncCursorUtc", "Id")
                        .HasDatabaseName("IX_Bins_Sync");

                    b.ToTable("Bins", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SyncCursorUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasComputedColumnSql("COALESCE(\"UpdatedAtUtc\", \"CreatedAtUtc\")", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("SyncCursorUtc", "Id")
                        .HasDatabaseName("IX_Companies_Sync");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("PolicyRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SourceCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetCompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TargetCompanyId");

                    b.HasIndex("SourceCompanyId", "TargetCompanyId")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("SourceCompanyId", "TargetCompanyId"), new[] { "IsEnabled", "PermissionLevel", "ConnectionType", "PolicyRevision" });

                    b.ToTable("CompanyConnections", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyConnections_ConnectionType", "\"ConnectionType\" IN ('ParentToParent', 'ParentToChild', 'ChildToParent', 'ChildToChild')");

                            t.HasCheckConstraint("CK_CompanyConnections_NoSelf", "\"SourceCompanyId\" <> \"TargetCompanyId\"");

                            t.HasCheckConstraint("CK_CompanyConnections_PermissionLevel", "\"PermissionLevel\" IN ('Read', 'Write', 'Full')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FilterValue")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyConnectionId");

                    b.ToTable("CompanyConnectionFilters", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyConnectionFilters_FilterType", "\"FilterType\" IN ('Region', 'Location', 'Warehouse', 'Category')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PermissionLevelOverride")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ScopeBinId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeRackId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeWarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyConnectionId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CompanyConnectionId"), new[] { "Level", "ScopeCompanyId", "ScopeLocationId", "ScopeWarehouseId", "ScopeRackId", "ScopeBinId", "PermissionLevelOverride" });

                    b.HasIndex("ScopeBinId");

                    b.HasIndex("ScopeCompanyId");

                    b.HasIndex("ScopeLocationId");

                    b.HasIndex("ScopeRackId");

                    b.HasIndex("ScopeWarehouseId");

                    b.ToTable("CompanyConnectionScopes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyConnectionScopes_Level", "\"Level\" IN ('Company', 'Location', 'Warehouse', 'Rack', 'Bin')");

                            t.HasCheckConstraint("CK_ConnScope_LevelMatches", "(\"Level\" = 'Company'   AND \"ScopeCompanyId\"   IS NOT NULL) OR(\"Level\" = 'Location'  AND \"ScopeLocationId\"  IS NOT NULL) OR(\"Level\" = 'Warehouse' AND \"ScopeWarehouseId\" IS NOT NULL) OR(\"Level\" = 'Rack'      AND \"ScopeRackId\"      IS NOT NULL) OR(\"Level\" = 'Bin'       AND \"ScopeBinId\"       IS NOT NULL)");

                            t.HasCheckConstraint("CK_ConnScope_OneTarget", "(CASE WHEN \"ScopeCompanyId\"   IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"ScopeLocationId\"  IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"ScopeWarehouseId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"ScopeRackId\"      IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"ScopeBinId\"       IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("SyncCursorUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasComputedColumnSql("COALESCE(\"UpdatedAtUtc\", \"CreatedAtUtc\")", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("CompanyId", "Barcode")
                        .HasFilter("\"Barcode\" IS NOT NULL");

                    b.HasIndex("CompanyId", "Sku")
                        .IsUnique();

                    b.HasIndex("CompanyId", "SyncCursorUtc", "Id")
                        .HasDatabaseName("IX_InventoryItems_Sync");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.InventorySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("VarianceThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("VarianceThresholdType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("InventorySettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventorySettings_VarianceThresholdType", "\"VarianceThresholdType\" IN ('AbsoluteQuantity', 'Percentage')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long?>("BaseDestinationStockVersion")
                        .HasColumnType("bigint");

                    b.Property<long?>("BaseSourceStockVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClientCreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationBinId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid?>("ReversalOfTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceBinId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SyncCursorUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasComputedColumnSql("COALESCE(\"UpdatedAtUtc\", \"CreatedAtUtc\")", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationBinId")
                        .HasFilter("\"DestinationBinId\" IS NOT NULL");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("ReversalOfTransactionId");

                    b.HasIndex("SourceBinId")
                        .HasFilter("\"SourceBinId\" IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex("CompanyId", "CreatedAtUtc");

                    b.HasIndex("CompanyId", "SyncCursorUtc", "Id")
                        .HasDatabaseName("IX_InventoryTransactions_Sync");

                    b.ToTable("InventoryTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_InvTxn_AdjustmentReason", "\"TransactionType\" <> 'Adjustment' OR \"AdjustmentReason\" IS NOT NULL");

                            t.HasCheckConstraint("CK_InvTxn_TypeShape", "(\"TransactionType\" = 'Receive'    AND \"SourceBinId\" IS NULL     AND \"DestinationBinId\" IS NOT NULL AND \"Quantity\" > 0) OR (\"TransactionType\" = 'Transfer'   AND \"SourceBinId\" IS NOT NULL AND \"DestinationBinId\" IS NOT NULL AND \"SourceBinId\" <> \"DestinationBinId\" AND \"Quantity\" > 0) OR (\"TransactionType\" = 'Adjustment' AND \"SourceBinId\" IS NOT NULL AND \"DestinationBinId\" IS NULL     AND \"Quantity\" <> 0)");

                            t.HasCheckConstraint("CK_InventoryTransactions_Status", "\"Status\" IN ('Applied', 'Rejected')");

                            t.HasCheckConstraint("CK_InventoryTransactions_TransactionType", "\"TransactionType\" IN ('Receive', 'Transfer', 'Adjustment')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SyncCursorUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasComputedColumnSql("COALESCE(\"UpdatedAtUtc\", \"CreatedAtUtc\")", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId");

                    b.HasIndex("CompanyId", "Region");

                    b.HasIndex("CompanyId", "SyncCursorUtc", "Id")
                        .HasDatabaseName("IX_Locations_Sync");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Rack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SyncCursorUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasComputedColumnSql("COALESCE(\"UpdatedAtUtc\", \"CreatedAtUtc\")", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("CompanyId", "SyncCursorUtc", "Id")
                        .HasDatabaseName("IX_Racks_Sync");

                    b.ToTable("Racks", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.ScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RawCode")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid?>("ResolvedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolvedType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("ScannedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex("CompanyId", "RawCode");

                    b.HasIndex("CompanyId", "ScannedAtUtc");

                    b.HasIndex("ScannedByUserId", "ScannedAtUtc");

                    b.ToTable("ScanEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_ScanEvents_ResolvedType", "\"ResolvedType\" IN ('Sku', 'Location', 'Asset', 'NoMatch', 'Blocked')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.StockCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdjustmentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long?>("BaseStockVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BinId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClientCreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CountedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SyncCursorUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasComputedColumnSql("COALESCE(\"UpdatedAtUtc\", \"CreatedAtUtc\")", true);

                    b.Property<decimal>("SystemQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("Variance")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasComputedColumnSql("\"CountedQuantity\" - \"SystemQuantity\"", true);

                    b.Property<decimal>("VarianceThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("VarianceThresholdType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentTransactionId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("BinId");

                    b.HasIndex("CountedByUserId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("TenantId");

                    b.HasIndex("CompanyId", "Status")
                        .HasFilter("\"Status\" = 'PendingApproval'");

                    b.HasIndex("CompanyId", "SyncCursorUtc", "Id")
                        .HasDatabaseName("IX_StockCounts_Sync");

                    b.ToTable("StockCounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockCounts_CountedNonNegative", "\"CountedQuantity\" >= 0");

                            t.HasCheckConstraint("CK_StockCounts_Status", "\"Status\" IN ('Completed', 'PendingApproval', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("CK_StockCounts_VarianceThresholdType", "\"VarianceThresholdType\" IN ('AbsoluteQuantity', 'Percentage')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.StockLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BinId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SyncCursorUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasComputedColumnSql("COALESCE(\"UpdatedAtUtc\", \"CreatedAtUtc\")", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BinId");

                    b.HasIndex("TenantId");

                    b.HasIndex("CompanyId", "InventoryItemId");

                    b.HasIndex("InventoryItemId", "BinId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "SyncCursorUtc", "Id")
                        .HasDatabaseName("IX_StockLevels_Sync");

                    b.ToTable("StockLevels", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockLevels_NonNegative", "\"QuantityOnHand\" >= 0");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.ToTable("Tenants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tenants_Kind", "\"Kind\" IN ('Parent', 'Child')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ActivatedDeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActivationKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ActivationResetAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ActivationResetByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ActivationKeyHash")
                        .IsUnique();

                    b.HasIndex("ActivationResetByUserId");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_ActivationStatus", "\"ActivationStatus\" IN ('NotActivated', 'Activated')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserCompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("UserCompanyMemberships", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiveCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCompanyId");

                    b.HasIndex("ActiveLocationId");

                    b.HasIndex("RefreshTokenHash");

                    b.HasIndex("UserId")
                        .HasFilter("\"RevokedAtUtc\" IS NULL");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SyncCursorUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasComputedColumnSql("COALESCE(\"UpdatedAtUtc\", \"CreatedAtUtc\")", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("CompanyId", "SyncCursorUtc", "Id")
                        .HasDatabaseName("IX_Warehouses_Sync");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Bin", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Rack", "Rack")
                        .WithMany("Bins")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Company", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Tenant", "Tenant")
                        .WithMany("Companies")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnection", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "SourceCompany")
                        .WithMany()
                        .HasForeignKey("SourceCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Company", "TargetCompany")
                        .WithMany()
                        .HasForeignKey("TargetCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceCompany");

                    b.Navigation("TargetCompany");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionFilter", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.CompanyConnection", "Connection")
                        .WithMany("Filters")
                        .HasForeignKey("CompanyConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionScope", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.CompanyConnection", "Connection")
                        .WithMany("Scopes")
                        .HasForeignKey("CompanyConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Bin", null)
                        .WithMany()
                        .HasForeignKey("ScopeBinId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("ScopeCompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("ScopeLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Rack", null)
                        .WithMany()
                        .HasForeignKey("ScopeRackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("ScopeWarehouseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.InventoryItem", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.InventorySettings", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.InventoryTransaction", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Bin", "DestinationBin")
                        .WithMany()
                        .HasForeignKey("DestinationBinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAMS.Api.Common.Domain.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.InventoryTransaction", "ReversalOf")
                        .WithMany()
                        .HasForeignKey("ReversalOfTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAMS.Api.Common.Domain.Bin", "SourceBin")
                        .WithMany()
                        .HasForeignKey("SourceBinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DestinationBin");

                    b.Navigation("InventoryItem");

                    b.Navigation("ReversalOf");

                    b.Navigation("SourceBin");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Location", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "Company")
                        .WithMany("Locations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Rack", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Warehouse", "Warehouse")
                        .WithMany("Racks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.ScanEvent", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.User", "ScannedByUser")
                        .WithMany()
                        .HasForeignKey("ScannedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScannedByUser");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.StockCount", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.InventoryTransaction", "AdjustmentTransaction")
                        .WithMany()
                        .HasForeignKey("AdjustmentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAMS.Api.Common.Domain.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAMS.Api.Common.Domain.Bin", "Bin")
                        .WithMany()
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.User", "CountedByUser")
                        .WithMany()
                        .HasForeignKey("CountedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdjustmentTransaction");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Bin");

                    b.Navigation("CountedByUser");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.StockLevel", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Bin", "Bin")
                        .WithMany()
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.InventoryItem", "InventoryItem")
                        .WithMany("StockLevels")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bin");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.User", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.User", "ActivationResetByUser")
                        .WithMany()
                        .HasForeignKey("ActivationResetByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActivationResetByUser");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserCompanyMembership", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAMS.Api.Common.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserSession", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "ActiveCompany")
                        .WithMany()
                        .HasForeignKey("ActiveCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Location", "ActiveLocation")
                        .WithMany()
                        .HasForeignKey("ActiveLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAMS.Api.Common.Domain.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveCompany");

                    b.Navigation("ActiveLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Warehouse", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Location", "Location")
                        .WithMany("Warehouses")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Company", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnection", b =>
                {
                    b.Navigation("Filters");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.InventoryItem", b =>
                {
                    b.Navigation("StockLevels");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Location", b =>
                {
                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Rack", b =>
                {
                    b.Navigation("Bins");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Tenant", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Warehouse", b =>
                {
                    b.Navigation("Racks");
                });
#pragma warning restore 612, 618
        }
    }
}
