// <auto-generated />
using System;
using IAMS.Api.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IAMS.Api.Common.Persistence.Migrations
{
    [DbContext(typeof(IamsDbContext))]
    [Migration("20260909151838_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IAMS.Api.Common.Domain.Bin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RackId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Bins", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("PolicyRevision")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SourceCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TargetCompanyId");

                    b.HasIndex("SourceCompanyId", "TargetCompanyId")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SourceCompanyId", "TargetCompanyId"), new[] { "IsEnabled", "PermissionLevel", "ConnectionType", "PolicyRevision" });

                    b.ToTable("CompanyConnections", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyConnections_ConnectionType", "[ConnectionType] IN ('ParentToParent', 'ParentToChild', 'ChildToParent', 'ChildToChild')");

                            t.HasCheckConstraint("CK_CompanyConnections_NoSelf", "[SourceCompanyId] <> [TargetCompanyId]");

                            t.HasCheckConstraint("CK_CompanyConnections_PermissionLevel", "[PermissionLevel] IN ('Read', 'Write', 'Full')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FilterValue")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyConnectionId");

                    b.ToTable("CompanyConnectionFilters", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyConnectionFilters_FilterType", "[FilterType] IN ('Region', 'Location', 'Warehouse', 'Category')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PermissionLevelOverride")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ScopeBinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScopeCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScopeLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScopeRackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScopeWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyConnectionId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CompanyConnectionId"), new[] { "Level", "ScopeCompanyId", "ScopeLocationId", "ScopeWarehouseId", "ScopeRackId", "ScopeBinId", "PermissionLevelOverride" });

                    b.HasIndex("ScopeBinId");

                    b.HasIndex("ScopeCompanyId");

                    b.HasIndex("ScopeLocationId");

                    b.HasIndex("ScopeRackId");

                    b.HasIndex("ScopeWarehouseId");

                    b.ToTable("CompanyConnectionScopes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyConnectionScopes_Level", "[Level] IN ('Company', 'Location', 'Warehouse', 'Rack', 'Bin')");

                            t.HasCheckConstraint("CK_ConnScope_LevelMatches", "([Level] = 'Company'   AND [ScopeCompanyId]   IS NOT NULL) OR([Level] = 'Location'  AND [ScopeLocationId]  IS NOT NULL) OR([Level] = 'Warehouse' AND [ScopeWarehouseId] IS NOT NULL) OR([Level] = 'Rack'      AND [ScopeRackId]      IS NOT NULL) OR([Level] = 'Bin'       AND [ScopeBinId]       IS NOT NULL)");

                            t.HasCheckConstraint("CK_ConnScope_OneTarget", "(CASE WHEN [ScopeCompanyId]   IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [ScopeLocationId]  IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [ScopeWarehouseId] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [ScopeRackId]      IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [ScopeBinId]       IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId");

                    b.HasIndex("CompanyId", "Region");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("ChallengeToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ResendAvailableAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResendCount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeToken")
                        .IsUnique();

                    b.HasIndex("UserId", "Purpose")
                        .HasFilter("[ConsumedAtUtc] IS NULL");

                    b.ToTable("OtpChallenges", null, t =>
                        {
                            t.HasCheckConstraint("CK_OtpChallenges_Channel", "[Channel] IN ('Email', 'Sms', 'Authenticator')");

                            t.HasCheckConstraint("CK_OtpChallenges_Purpose", "[Purpose] IN ('Login')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Rack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Racks", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.ToTable("Tenants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tenants_Kind", "[Kind] IN ('Parent', 'Child')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserCompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("UserCompanyMemberships", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActiveCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsTwoFactorComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCompanyId");

                    b.HasIndex("ActiveLocationId");

                    b.HasIndex("RefreshTokenHash");

                    b.HasIndex("UserId")
                        .HasFilter("[RevokedAtUtc] IS NULL");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserTwoFactorSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("SharedSecret")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId");

                    b.ToTable("UserTwoFactorSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserTwoFactorSettings_Channel", "[Channel] IN ('Email', 'Sms', 'Authenticator')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Bin", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Rack", "Rack")
                        .WithMany("Bins")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Company", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Tenant", "Tenant")
                        .WithMany("Companies")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnection", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "SourceCompany")
                        .WithMany()
                        .HasForeignKey("SourceCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Company", "TargetCompany")
                        .WithMany()
                        .HasForeignKey("TargetCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceCompany");

                    b.Navigation("TargetCompany");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionFilter", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.CompanyConnection", "Connection")
                        .WithMany("Filters")
                        .HasForeignKey("CompanyConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionScope", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.CompanyConnection", "Connection")
                        .WithMany("Scopes")
                        .HasForeignKey("CompanyConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Bin", null)
                        .WithMany()
                        .HasForeignKey("ScopeBinId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("ScopeCompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("ScopeLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Rack", null)
                        .WithMany()
                        .HasForeignKey("ScopeRackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("ScopeWarehouseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Location", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "Company")
                        .WithMany("Locations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.OtpChallenge", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Rack", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Warehouse", "Warehouse")
                        .WithMany("Racks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserCompanyMembership", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAMS.Api.Common.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserSession", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "ActiveCompany")
                        .WithMany()
                        .HasForeignKey("ActiveCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Location", "ActiveLocation")
                        .WithMany()
                        .HasForeignKey("ActiveLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAMS.Api.Common.Domain.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveCompany");

                    b.Navigation("ActiveLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserTwoFactorSetting", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.User", "User")
                        .WithOne("TwoFactorSetting")
                        .HasForeignKey("IAMS.Api.Common.Domain.UserTwoFactorSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Warehouse", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Location", "Location")
                        .WithMany("Warehouses")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Company", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnection", b =>
                {
                    b.Navigation("Filters");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Location", b =>
                {
                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Rack", b =>
                {
                    b.Navigation("Bins");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Tenant", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Sessions");

                    b.Navigation("TwoFactorSetting");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Warehouse", b =>
                {
                    b.Navigation("Racks");
                });
#pragma warning restore 612, 618
        }
    }
}
