// <auto-generated />
using System;
using IAMS.Api.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IAMS.Api.Common.Persistence.Migrations
{
    [DbContext(typeof(IamsDbContext))]
    [Migration("20260914104810_ActivationKeyAuthentication")]
    partial class ActivationKeyAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IAMS.Api.Common.Domain.Bin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RackId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Bins", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("PolicyRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SourceCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetCompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TargetCompanyId");

                    b.HasIndex("SourceCompanyId", "TargetCompanyId")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("SourceCompanyId", "TargetCompanyId"), new[] { "IsEnabled", "PermissionLevel", "ConnectionType", "PolicyRevision" });

                    b.ToTable("CompanyConnections", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyConnections_ConnectionType", "\"ConnectionType\" IN ('ParentToParent', 'ParentToChild', 'ChildToParent', 'ChildToChild')");

                            t.HasCheckConstraint("CK_CompanyConnections_NoSelf", "\"SourceCompanyId\" <> \"TargetCompanyId\"");

                            t.HasCheckConstraint("CK_CompanyConnections_PermissionLevel", "\"PermissionLevel\" IN ('Read', 'Write', 'Full')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FilterValue")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyConnectionId");

                    b.ToTable("CompanyConnectionFilters", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyConnectionFilters_FilterType", "\"FilterType\" IN ('Region', 'Location', 'Warehouse', 'Category')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PermissionLevelOverride")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ScopeBinId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeRackId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeWarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyConnectionId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CompanyConnectionId"), new[] { "Level", "ScopeCompanyId", "ScopeLocationId", "ScopeWarehouseId", "ScopeRackId", "ScopeBinId", "PermissionLevelOverride" });

                    b.HasIndex("ScopeBinId");

                    b.HasIndex("ScopeCompanyId");

                    b.HasIndex("ScopeLocationId");

                    b.HasIndex("ScopeRackId");

                    b.HasIndex("ScopeWarehouseId");

                    b.ToTable("CompanyConnectionScopes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyConnectionScopes_Level", "\"Level\" IN ('Company', 'Location', 'Warehouse', 'Rack', 'Bin')");

                            t.HasCheckConstraint("CK_ConnScope_LevelMatches", "(\"Level\" = 'Company'   AND \"ScopeCompanyId\"   IS NOT NULL) OR(\"Level\" = 'Location'  AND \"ScopeLocationId\"  IS NOT NULL) OR(\"Level\" = 'Warehouse' AND \"ScopeWarehouseId\" IS NOT NULL) OR(\"Level\" = 'Rack'      AND \"ScopeRackId\"      IS NOT NULL) OR(\"Level\" = 'Bin'       AND \"ScopeBinId\"       IS NOT NULL)");

                            t.HasCheckConstraint("CK_ConnScope_OneTarget", "(CASE WHEN \"ScopeCompanyId\"   IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"ScopeLocationId\"  IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"ScopeWarehouseId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"ScopeRackId\"      IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"ScopeBinId\"       IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId");

                    b.HasIndex("CompanyId", "Region");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Rack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Racks", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.ToTable("Tenants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tenants_Kind", "\"Kind\" IN ('Parent', 'Child')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ActivatedDeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActivationKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ActivationResetAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ActivationResetByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ActivationKeyHash")
                        .IsUnique();

                    b.HasIndex("ActivationResetByUserId");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_ActivationStatus", "\"ActivationStatus\" IN ('NotActivated', 'Activated')");
                        });
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserCompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("UserCompanyMemberships", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiveCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCompanyId");

                    b.HasIndex("ActiveLocationId");

                    b.HasIndex("RefreshTokenHash");

                    b.HasIndex("UserId")
                        .HasFilter("\"RevokedAtUtc\" IS NULL");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Bin", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Rack", "Rack")
                        .WithMany("Bins")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Company", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Tenant", "Tenant")
                        .WithMany("Companies")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnection", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "SourceCompany")
                        .WithMany()
                        .HasForeignKey("SourceCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Company", "TargetCompany")
                        .WithMany()
                        .HasForeignKey("TargetCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceCompany");

                    b.Navigation("TargetCompany");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionFilter", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.CompanyConnection", "Connection")
                        .WithMany("Filters")
                        .HasForeignKey("CompanyConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnectionScope", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.CompanyConnection", "Connection")
                        .WithMany("Scopes")
                        .HasForeignKey("CompanyConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Bin", null)
                        .WithMany()
                        .HasForeignKey("ScopeBinId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("ScopeCompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("ScopeLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Rack", null)
                        .WithMany()
                        .HasForeignKey("ScopeRackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IAMS.Api.Common.Domain.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("ScopeWarehouseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Location", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "Company")
                        .WithMany("Locations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Rack", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Warehouse", "Warehouse")
                        .WithMany("Racks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.User", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.User", "ActivationResetByUser")
                        .WithMany()
                        .HasForeignKey("ActivationResetByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActivationResetByUser");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserCompanyMembership", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAMS.Api.Common.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.UserSession", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Company", "ActiveCompany")
                        .WithMany()
                        .HasForeignKey("ActiveCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAMS.Api.Common.Domain.Location", "ActiveLocation")
                        .WithMany()
                        .HasForeignKey("ActiveLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAMS.Api.Common.Domain.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveCompany");

                    b.Navigation("ActiveLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Warehouse", b =>
                {
                    b.HasOne("IAMS.Api.Common.Domain.Location", "Location")
                        .WithMany("Warehouses")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Company", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.CompanyConnection", b =>
                {
                    b.Navigation("Filters");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Location", b =>
                {
                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Rack", b =>
                {
                    b.Navigation("Bins");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Tenant", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("IAMS.Api.Common.Domain.Warehouse", b =>
                {
                    b.Navigation("Racks");
                });
#pragma warning restore 612, 618
        }
    }
}
